name: "Run script and add tag"
on: 
  pull_request:
    branches:
      - main
  # push:
  #   branches:
  #     - main
env: 
  GH_TOKEN: ${{ secrets.GITHUB_ACCESS_TOKEN }}

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Set Up Java
        uses: actions/setup-java@v3.12.0
        with:
          distribution: 'oracle'
          java-version: '17'
      - name: Set Up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.5'
          channel: 'stable'
      - name: Install Dependencies
        run: flutter pub get
      - name: Upload APK 
        uses: actions/upload-artifact@v4
        with:
          name: app-debug.apk
          path: build/apk/app-debug.apk
      - name: Job Summary
        run: |
          echo "Build APK finished"
  add-label:
    name: Add Label to PR
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
      issues: write
    steps:
      - uses: actions-ecosystem/action-add-labels@v1
        with: 
          github_token: ${{ env.GH_TOKEN }}
          labels: need-tester
      - name: Job Summary
        run: echo "Added Label to PR"
  run-script: 
    name: Run Script and edit PR Description
    runs-on: ubuntu-latest
    steps: 
      - name: Setup Python for script
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Run a script
        id: run_script
        run: python .github/scripts/get_link_script.py

      - name: Edit PR
        uses: actions/github-script@v7
        with:
          script: |
            await github.rest.pulls.update({
              pull_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: ${{ steps.run_script.outputs.body }}
            })
      - name: Job Summary
        run: echo "Edited description of PR"

      